{
 "about": {
  "channels": [
   "conda-forge",
   "defaults"
  ],
  "conda_build_version": "3.20.2",
  "conda_private": false,
  "conda_version": "4.8.4",
  "dev_url": "https://github.com/ageitgey/face_recognition",
  "doc_url": "https://face-recognition.readthedocs.io/en/latest/face_recognition.html",
  "env_vars": {
   "CIO_TEST": "<not set>"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "ndmaxar",
    "rluria14",
    "oblute"
   ]
  },
  "home": "https://github.com/ageitgey/face_recognition",
  "identifiers": [],
  "keywords": [],
  "license": "MIT",
  "license_family": "MIT",
  "license_file": "LICENSE",
  "root_pkgs": [
   "idna 2.10 pyh9f0ad1d_0",
   "ripgrep 12.1.1 h516909a_0",
   "pytz 2020.1 pyh9f0ad1d_0",
   "pkginfo 1.5.0.1 py_0",
   "lzo 2.10 h516909a_1000",
   "perl 5.26.2 h516909a_1006",
   "cffi 1.14.1 py37h2b28604_0",
   "krb5 1.17.1 hfafb76e_3",
   "libedit 3.1.20191231 he28a2e2_2",
   "certifi 2020.6.20 py37hc8dfbb8_0",
   "openssl 1.1.1g h516909a_1",
   "libcurl 7.71.1 hcdd3856_5",
   "gettext 0.19.8.1 hc5be6a0_1002",
   "libgomp 9.3.0 h24d8f2e_16",
   "pyyaml 5.3.1 py37h8f50634_0",
   "nbformat 5.0.7 py_0",
   "curl 7.71.1 he644dc0_5",
   "libssh2 1.9.0 hab1572f_5",
   "jsonschema 3.2.0 py37hc8dfbb8_1",
   "libev 4.33 h516909a_1",
   "patchelf 0.11 he1b5a44_0",
   "python 3.7.8 h6f2ec95_1_cpython",
   "tk 8.6.10 hed695b0_0",
   "expat 2.2.9 he1b5a44_2",
   "libarchive 3.3.3 hddc7a2b_1008",
   "pip 20.2.3 py_0",
   "libiconv 1.16 h516909a_0",
   "pysocks 1.7.1 py37hc8dfbb8_1",
   "pycparser 2.20 pyh9f0ad1d_2",
   "soupsieve 2.0.1 py_1",
   "wheel 0.35.1 pyh9f0ad1d_0",
   "importlib_metadata 1.7.0 0",
   "pyrsistent 0.17.3 py37h8f50634_0",
   "tini 0.18.0 h14c3975_1001",
   "pyopenssl 19.1.0 py_1",
   "lz4-c 1.9.2 he1b5a44_3",
   "glob2 0.7 py_0",
   "filelock 3.0.12 pyh9f0ad1d_0",
   "pycosat 0.6.3 py37h8f50634_1004",
   "git 2.28.0 pl526h5e3e691_1",
   "traitlets 5.0.4 py_0",
   "liblief 0.10.1 he1b5a44_1",
   "_openmp_mutex 4.5 1_gnu",
   "tqdm 4.49.0 pyh9f0ad1d_0",
   "libffi 3.2.1 he1b5a44_1007",
   "libstdcxx-ng 9.3.0 hdf63c60_16",
   "zlib 1.2.11 h516909a_1009",
   "ca-certificates 2020.6.20 hecda079_0",
   "ipython_genutils 0.2.0 py_1",
   "six 1.15.0 pyh9f0ad1d_0",
   "patch 2.7.6 h14c3975_1001",
   "jupyter_core 4.6.3 py37hc8dfbb8_1",
   "readline 8.0 he28a2e2_2",
   "python-libarchive-c 2.9 py37_0",
   "sqlite 3.33.0 h4cf870e_0",
   "anaconda-client 1.7.2 py_0",
   "ruamel_yaml 0.15.80 py37h8f50634_1002",
   "importlib-metadata 1.7.0 py37hc8dfbb8_0",
   "brotlipy 0.7.0 py37h8f50634_1000",
   "conda-package-handling 1.7.0 py37h8f50634_4",
   "xz 5.2.5 h516909a_1",
   "_libgcc_mutex 0.1 conda_forge",
   "python_abi 3.7 1_cp37m",
   "jinja2 2.11.2 pyh9f0ad1d_0",
   "psutil 5.7.2 py37h8f50634_0",
   "bzip2 1.0.8 h516909a_3",
   "setuptools 49.6.0 py37hc8dfbb8_0",
   "urllib3 1.25.10 py_0",
   "conda 4.8.4 py37hc8dfbb8_2",
   "clyent 1.2.2 py_1",
   "libgcc-ng 9.3.0 h24d8f2e_16",
   "libnghttp2 1.41.0 h8cfc5f6_2",
   "zstd 1.4.5 h6597ccf_2",
   "attrs 20.2.0 pyh9f0ad1d_0",
   "pcre 8.44 he1b5a44_0",
   "py-lief 0.10.1 py37h3340039_1",
   "conda-build 3.20.2 py37hc8dfbb8_0",
   "c-ares 1.16.1 h516909a_3",
   "cryptography 3.1 py37hb09aad4_0",
   "python-dateutil 2.8.1 py_0",
   "libxml2 2.9.10 h68273f3_2",
   "yaml 0.2.5 h516909a_0",
   "ld_impl_linux-64 2.35 h769bd43_9",
   "ncurses 6.2 he1b5a44_1",
   "beautifulsoup4 4.9.1 py_1",
   "su-exec 0.2 h516909a_1002",
   "chardet 3.0.4 py37hc8dfbb8_1006",
   "requests 2.24.0 pyh9f0ad1d_0",
   "icu 67.1 he1b5a44_0",
   "zipp 3.1.0 py_0",
   "markupsafe 1.1.1 py37h8f50634_1",
   "conda-env 2.6.0 1",
   "oniguruma 6.9.3 h516909a_0",
   "jq 1.6 h14c3975_1000",
   "shyaml 0.6.1 py_0",
   "conda-forge-ci-setup 3.2.1 py37h71091ce_0",
   "click 7.1.2 pyh9f0ad1d_0"
  ],
  "summary": "Recognize faces from Python or from the command line",
  "tags": []
 },
 "conda_build_config": {
  "CI": "azure",
  "c_compiler": "gcc",
  "channel_sources": "conda-forge,defaults",
  "channel_targets": "conda-forge main",
  "cpu_optimization_target": "nocona",
  "cran_mirror": "https://cran.r-project.org",
  "cxx_compiler": "gxx",
  "docker_image": "condaforge/linux-anvil-comp7",
  "extend_keys": [
   "pin_run_as_build",
   "ignore_version",
   "ignore_build_only_deps",
   "extend_keys"
  ],
  "fortran_compiler": "gfortran",
  "ignore_build_only_deps": [
   "python",
   "numpy"
  ],
  "lua": "5",
  "numpy": "1.11",
  "perl": "5.26.2",
  "pin_run_as_build": {
   "python": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   },
   "r-base": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   }
  },
  "python": "3.6.* *_cpython",
  "r_base": "3.5",
  "target_platform": "linux-64"
 },
 "files": [
  "site-packages/face_recognition-1.3.0.dist-info/AUTHORS.rst",
  "site-packages/face_recognition-1.3.0.dist-info/INSTALLER",
  "site-packages/face_recognition-1.3.0.dist-info/LICENSE",
  "site-packages/face_recognition-1.3.0.dist-info/METADATA",
  "site-packages/face_recognition-1.3.0.dist-info/RECORD",
  "site-packages/face_recognition-1.3.0.dist-info/REQUESTED",
  "site-packages/face_recognition-1.3.0.dist-info/WHEEL",
  "site-packages/face_recognition-1.3.0.dist-info/direct_url.json",
  "site-packages/face_recognition/__init__.py",
  "site-packages/face_recognition/api.py",
  "site-packages/face_recognition/face_detection_cli.py",
  "site-packages/face_recognition/face_recognition_cli.py"
 ],
 "index": {
  "arch": null,
  "build": "pyh9f0ad1d_1",
  "build_number": 1,
  "depends": [
   "click >=6.0",
   "dlib >=19.7",
   "face_recognition_models >=0.3.0",
   "numpy >=1.8",
   "pillow",
   "python"
  ],
  "license": "MIT",
  "license_family": "MIT",
  "name": "face_recognition",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1600102192967,
  "version": "1.3.0"
 },
 "metadata_version": 1,
 "name": "face_recognition",
 "raw_recipe": "{% set name = \"face_recognition\" %}\n{% set version = \"1.3.0\" %}\n\npackage:\n  name: \"{{ name|lower }}\"\n  version: \"{{ version }}\"\n\nsource:\n  url: \"https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\"\n  sha256: 5e5efdd1686aa566af0d3cc1313b131e4b197657a8ffd03669e6d3fad92705ec\n\nbuild:\n  number: 1\n  noarch: python\n  entry_points:\n    - face_recognition=face_recognition.face_recognition_cli:main\n    - face_detection=face_recognition.face_detection_cli:main\n  script: \"{{ PYTHON }} -m pip install . -vv\"\n\nrequirements:\n  host:\n    - pip\n    - python\n  run:\n    - click >=6.0\n    - dlib >=19.7\n    - face_recognition_models >=0.3.0\n    - numpy >=1.8\n    - pillow\n    - python\n\ntest:\n  imports:\n    - face_recognition\n  commands:\n    - face_recognition --help\n    - face_detection --help\n\nabout:\n  home: https://github.com/ageitgey/face_recognition\n  license: MIT\n  license_family: MIT\n  license_file: LICENSE\n  summary: \"Recognize faces from Python or from the command line\"\n  doc_url: https://face-recognition.readthedocs.io/en/latest/face_recognition.html\n  dev_url: https://github.com/ageitgey/face_recognition\n\nextra:\n  recipe-maintainers:\n    - ndmaxar\n    - rluria14\n    - oblute\n",
 "rendered_recipe": {
  "about": {
   "dev_url": "https://github.com/ageitgey/face_recognition",
   "doc_url": "https://face-recognition.readthedocs.io/en/latest/face_recognition.html",
   "home": "https://github.com/ageitgey/face_recognition",
   "license": "MIT",
   "license_family": "MIT",
   "license_file": "LICENSE",
   "summary": "Recognize faces from Python or from the command line"
  },
  "build": {
   "entry_points": [
    "face_detection=face_recognition.face_detection_cli:main",
    "face_recognition=face_recognition.face_recognition_cli:main"
   ],
   "noarch": "python",
   "number": "1",
   "script": "/home/conda/feedstock_root/build_artifacts/face_recognition_1600102073710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -m pip install . -vv",
   "string": "pyh9f0ad1d_1"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "ndmaxar",
    "oblute",
    "rluria14"
   ]
  },
  "package": {
   "name": "face_recognition",
   "version": "1.3.0"
  },
  "requirements": {
   "host": [
    "_libgcc_mutex 0.1 conda_forge",
    "_openmp_mutex 4.5 1_gnu",
    "ca-certificates 2020.6.20 hecda079_0",
    "certifi 2020.6.20 py36h9f0ad1d_0",
    "ld_impl_linux-64 2.35 h769bd43_9",
    "libffi 3.2.1 he1b5a44_1007",
    "libgcc-ng 9.3.0 h24d8f2e_16",
    "libgomp 9.3.0 h24d8f2e_16",
    "libstdcxx-ng 9.3.0 hdf63c60_16",
    "ncurses 6.2 he1b5a44_1",
    "openssl 1.1.1g h516909a_1",
    "pip 20.2.3 py_0",
    "python 3.6.11 h4d41432_2_cpython",
    "python_abi 3.6 1_cp36m",
    "readline 8.0 he28a2e2_2",
    "setuptools 49.6.0 py36h9f0ad1d_0",
    "sqlite 3.33.0 h4cf870e_0",
    "tk 8.6.10 hed695b0_0",
    "wheel 0.35.1 pyh9f0ad1d_0",
    "xz 5.2.5 h516909a_1",
    "zlib 1.2.11 h516909a_1009"
   ],
   "run": [
    "click >=6.0",
    "dlib >=19.7",
    "face_recognition_models >=0.3.0",
    "numpy >=1.8",
    "pillow",
    "python"
   ]
  },
  "source": {
   "sha256": "5e5efdd1686aa566af0d3cc1313b131e4b197657a8ffd03669e6d3fad92705ec",
   "url": "https://pypi.io/packages/source/f/face_recognition/face_recognition-1.3.0.tar.gz"
  },
  "test": {
   "commands": [
    "face_recognition --help",
    "face_detection --help"
   ],
   "imports": [
    "face_recognition"
   ]
  }
 },
 "version": "1.3.0"
}